_format_version: "2.1"
_transform: true

services:
- name: hello-world
  url: http://10.5.0.4:8000
  routes:
    - name: demo-service-route
      hosts:
        - demo-service.com

plugins:
  - name: token-introspection
    config:
      introspection_endpoint: https://10.5.0.3:4445/oauth2/introspect
      client_id: introspection-client
      client_secret: secret
      introspection_ssl_verify: false
      scope: ["mail"]
  - name: rate-limiting
    service: hello-world
    config:
      hour: 3
      policy: local
      # Limit the request by the Authorization header value - the token
      limit_by: header
      header_name: "Authorization"